import requests
import urllib.parse
import json
import os
from datetime import datetime

# 1. 환경변수 설정
SLACK_URL = os.environ['SLACK_WEBHOOK_URL']
NAVER_ID = os.environ['NAVER_CLIENT_ID']
NAVER_SECRET = os.environ['NAVER_CLIENT_SECRET']

# 2. 뉴스 검색 함수
def get_news(keyword, count):
    enc_text = urllib.parse.quote(keyword)
    # sort='sim': 정확도순, display=count: 개수
    url = f"https://openapi.naver.com/v1/search/news.json?query={enc_text}&display={count}&sort=sim"
    
    headers = {
        "X-Naver-Client-Id": NAVER_ID,
        "X-Naver-Client-Secret": NAVER_SECRET
    }
    
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            return response.json().get('items', [])
        return []
    except:
        return []

# 3. 메인 실행 함수
def send_alert():
    # 날짜 서식 (예: 2026. 02. 10. 화요일)
    today = datetime.now().strftime("%Y. %m. %d. (%a)")
    
    # 🎨 [설정] (보여질 제목, 실제 검색어, 가져올 개수)
    search_configs = [
        ("🚙 제주 렌터카", "제주 (렌터카 | 렌트카)", 3),
        ("🚕 제주 모빌리티", "제주 모빌리티", 1),
        ("🚙 쏘카(SOCAR)", "제주 쏘카", 1),
        ("🌴 제주 관광", "제주 관광", 3),
        ("✈️ 제주 공항", "제주 공항", 1),
        ("🌤️ 제주 날씨", "제주 예보", 1)
    ]
    
    # 🧱 [블록 킷] 메시지 구성 시작
    blocks = []
    
    # (1) 헤더 (가장 큰 제목)
    blocks.append({
        "type": "header",
        "text": {
            "type": "plain_text",
            "text": f"📅 {today} 뉴스 브리핑",
            "emoji": True
        }
    })
    
    # (2) 주제별 뉴스 블록 추가
    for display_title, keyword, count in search_configs:
        news_items = get_news(keyword, count)
        
        # 구분선 (주제마다 상단에 배치하여 깔끔하게 분리)
        blocks.append({"type": "divider"})
        
        # 주제 제목 (진하게)
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{display_title}*"
            }
        })
        
        if not news_items:
            # 뉴스가 없을 때 (작은 회색 글씨)
            blocks.append({
                "type": "context",
                "elements": [{"type": "mrkdwn", "text": "🚫 관련 최신 뉴스가 없습니다."}]
            })
        else:
            # 뉴스가 있을 때 (리스트 형태)
            news_text = ""
            for item in news_items:
                # 제목 정제 (따옴표 및 태그 제거)
                title = item['title'].replace('<b>', '').replace('</b>', '').replace('&quot;', "'")
                link = item['link']
                # • <링크|제목> 형태로 클릭 가능한 텍스트 생성
                news_text += f"• <{link}|{title}>\n"
            
            # 본문 추가
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": news_text
                }
            })

    # (3) 하단 푸터 (출처 표시)
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "📢 Generated by JejuBot | Data Source: Naver Search API"
            }
        ]
    })

    # 📨 전송 (blocks 파라미터 사용 - 이게 핵심!)
    payload = {
        "text": f"📅 {today} 제주 뉴스 브리핑이 도착했습니다.", # 알림 팝업용 텍스트
        "blocks": blocks
    }
    requests.post(SLACK_URL, data=json.dumps(payload))
    print("✅ 전송 완료")

if __name__ == "__main__":
    send_alert()
